# -*- coding: utf-8 -*-
import tkinter as tk
import tkinter as ttk

def title(root, tk):
    #タイトルを入れる。
    root.title("〇〇モジュール")
    root.geometry("850x1000")
    label1 = tk.Label(root, text="密粒度ｱｽﾌｧﾙﾄ混合物(13)　AM10:00")  #文字ラベル設定
    label1.place(x=50,y=30) 
    label2 = tk.Label(root, text="試験月日　　　2019　年　09　月　12　日")  #文字ラベル設定
    label2.place(x=500,y=10) # 場所を指定



def sample(root, ttk, tk, shiryou, r135):

    samples = {
	    '1': round(float(shiryou['1']),1),
	    '2': round(float(shiryou['2']),1),
	    '3': round(float(shiryou['3']),1),
	    '4': round(float(shiryou['2'])-float(shiryou['1']),1),
	    '5': round(float(shiryou['3'])-float(shiryou['1']),1),
	    '6': round(float(shiryou['2'])-float(shiryou['3']),1),
	    '7': str(round(float(shiryou['6'])/float(shiryou['4'])*100,2)),
	    '8': str(round(float(shiryou['6'])/float(shiryou['4'])*100-float(r135['total']),2))}



    #frame2を定義する
    frame2 = ttk.Frame(root)
    #frame2の中のラベルを作る
    label56 = tk.Label(frame2, text ="①", relief ="groove",width=5)
    label56.grid(row = 1, column = 0)
    label57 = tk.Label(frame2, text ="試料皿+ろ紙重量", relief ="groove",width=18)
    label57.grid(row = 1, column = 1)
    label58 = tk.Label(frame2, text =" ", relief ="groove",width=6)
    label58.grid(row = 1, column = 2)
    label59 = tk.Label(frame2, text =samples['1'], relief ="groove",width=10)
    label59.grid(row = 1, column = 3)
    label60 = tk.Label(frame2, text ="②", relief ="groove",width=5)
    label60.grid(row = 2, column = 0)
    label61 = tk.Label(frame2, text ="①+試料(抽出前)", relief ="groove",width=18)
    label61.grid(row = 2, column = 1)
    label62 = tk.Label(frame2, text =" ", relief ="groove",width=6)
    label62.grid(row = 2, column = 2)
    label63 = tk.Label(frame2, text =samples["2"], relief ="groove",width=10)
    label63.grid(row = 2, column = 3)
    label64 = tk.Label(frame2, text ="③", relief ="groove",width=5)
    label64.grid(row = 3, column = 0)
    label65 = tk.Label(frame2, text ="①+試料(抽出後)", relief ="groove",width=18)
    label65.grid(row = 3, column = 1)
    label66 = tk.Label(frame2, text =" ", relief ="groove",width=6)
    label66.grid(row = 3, column = 2)
    label67 = tk.Label(frame2, text =samples["3"], relief ="groove",width=10)
    label67.grid(row = 3, column = 3)
    label68 = tk.Label(frame2, text ="④", relief ="groove",width=5)
    label68.grid(row = 4, column = 0)
    label69 = tk.Label(frame2, text ="試料重量(抽出前)", relief ="groove",width=18)
    label69.grid(row = 4, column = 1)
    label70 = tk.Label(frame2, text ="②-①", relief ="groove",width=6)
    label70.grid(row = 4, column = 2)
    label71 = tk.Label(frame2, text =samples["4"], relief ="groove",width=10)
    label71.grid(row = 4, column = 3)
    label72 = tk.Label(frame2, text ="⑤", relief ="groove",width=5)
    label72.grid(row = 5, column = 0)
    label73 = tk.Label(frame2, text ="試料重量(抽出後)", relief ="groove",width=18)
    label73.grid(row = 5, column = 1)
    label74 = tk.Label(frame2, text ="③-①", relief ="groove",width=6)
    label74.grid(row = 5, column = 2)
    label75 = tk.Label(frame2, text =samples["5"], relief ="groove",width=10)
    label75.grid(row = 5, column = 3)
    label76 = tk.Label(frame2, text ="⑥", relief ="groove",width=5)
    label76.grid(row = 6, column = 0)
    label77 = tk.Label(frame2, text ="アスファルト重量", relief ="groove",width=18)
    label77.grid(row = 6, column = 1)
    label78 = tk.Label(frame2, text ="②-③", relief ="groove",width=6)
    label78.grid(row = 6, column = 2)
    label79 = tk.Label(frame2, text =samples["6"], relief ="groove",width=10)
    label79.grid(row = 6, column = 3)
    label80 = tk.Label(frame2, text ="⑦", relief ="groove",width=5)
    label80.grid(row = 7, column = 0)
    label81 = tk.Label(frame2, text ="アスファルト含有量(Wet)", relief ="groove",width=18)
    label81.grid(row = 7, column = 1)
    label82 = tk.Label(frame2, text ="⑥/④", relief ="groove",width=6)
    label82.grid(row = 7, column = 2)
    label83 = tk.Label(frame2, text =samples["7"]+"%", relief ="groove",width=10)
    label83.grid(row = 7, column = 3)
    label84 = tk.Label(frame2, text ="⑧", relief ="groove",width=5)
    label84.grid(row = 8, column = 0)
    label85 = tk.Label(frame2, text ="アスファルト含有率", relief ="groove",width=18)
    label85.grid(row = 8, column = 1)
    label86 = tk.Label(frame2, text ="⑥/④", relief ="groove",width=6)
    label86.grid(row = 8, column = 2)
    label87 = tk.Label(frame2, text =samples["8"]+"%", relief ="groove",width=10)
    label87.grid(row = 8, column = 3)
    #frame2の場所を指定する
    frame2.place(x=10,y=111)
    #frame5を定義する
    frame5 = ttk.Frame(root)
    label88 = tk.Label(frame5, text =" ", relief ="groove",width=5)
    label88.grid(row = 0, column = 0)
    label89 = tk.Label(frame5, text ="試料No.", relief ="groove",width=18)
    label89.grid(row = 0, column = 1)
    label90 = tk.Label(frame5, text =" ", relief ="groove",width=17)
    label90.grid(row = 0, column = 2)
    #frame5の場所を指定する
    frame5.place(x=10,y=90)
    
    return samples
    



def clas(root, tk, ttk, r135, r50):
    #frame3を定義する
    frame3 = ttk.Frame(root)
    #frameの中のラベルを作る
    label91 = tk.Label(frame3, text =" ", relief ="groove",width=12)
    label91.grid(row = 0, column = 0)
    label92 = tk.Label(frame3, text ="R13-5", relief ="groove",width=7)
    label92.grid(row = 0, column = 1)
    label93 = tk.Label(frame3, text ="R5-0", relief ="groove",width=7)
    label93.grid(row = 0, column = 2)
    label94 = tk.Label(frame3, text ="分級重量", relief ="groove",width=12)
    label94.grid(row = 1, column = 0)
    label95 = tk.Label(frame3, text =r135["weight"], relief ="groove",width=7)
    label95.grid(row = 1, column = 1)
    label96 = tk.Label(frame3, text =r50["weight"], relief ="groove",width=7)
    label96.grid(row = 1, column = 2)
    label94 = tk.Label(frame3, text ="分級比率", relief ="groove",width=12)
    label94.grid(row = 2, column = 0)
    label95 = tk.Label(frame3, text =r135["ratio"]+"%", relief ="groove",width=7)
    label95.grid(row = 2, column = 1)
    label96 = tk.Label(frame3, text =r50["ratio"]+"%", relief ="groove",width=7)
    label96.grid(row = 2, column = 2)
    label97 = tk.Label(frame3, text ="バット", relief ="groove",width=12)
    label97.grid(row = 3, column = 0)
    label98 = tk.Label(frame3, text =r135["bat"], relief ="groove",width=7)
    label98.grid(row = 3, column = 1)
    label99 = tk.Label(frame3, text =r50["bat"], relief ="groove",width=7)
    label99.grid(row = 3, column = 2)
    label100 = tk.Label(frame3, text ="バット+Wet", relief ="groove",width=12)
    label100.grid(row = 4, column = 0)
    label101 = tk.Label(frame3, text =r135["bat+wet"], relief ="groove",width=7)
    label101.grid(row = 4, column = 1)
    label102 = tk.Label(frame3, text =r50["bat+wet"], relief ="groove",width=7)
    label102.grid(row = 4, column = 2)
    label101 = tk.Label(frame3, text ="バット+Dry", relief ="groove",width=12)
    label101.grid(row = 5, column = 0)
    label102 = tk.Label(frame3, text =r135["bat+dry"], relief ="groove",width=7)
    label102.grid(row = 5, column = 1)
    label103 = tk.Label(frame3, text =r50["bat+dry"], relief ="groove",width=7)
    label103.grid(row = 5, column = 2)
    label104 = tk.Label(frame3, text ="含水比", relief ="groove",width=12)
    label104.grid(row = 6, column = 0)
    label105 = tk.Label(frame3, text =r135["moisture"]+"%", relief ="groove",width=7)
    label105.grid(row = 6, column = 1)
    label106 = tk.Label(frame3, text =r50["moisture"]+"%", relief ="groove",width=7)
    label106.grid(row = 6, column = 2)
    #frame3の場所を指定する
    frame3.place(x=10,y=310)
    #frame6を定義する
    frame6 = ttk.Frame(root)
    label107 = tk.Label(frame6, text ="合成含水比", relief ="groove",width=12)
    label107.grid(row = 7, column = 0)
    label108 = tk.Label(frame6, text =r135["total"]+"%", relief ="groove",width=15)
    label108.grid(row = 7, column = 1)
    #frame6の場所を指定する
    frame6.place(x=10,y=457)




def penetration(root, ttk, tk, shinnyu):
    average = {
    	'av':round(((float(shinnyu['first'])+float(shinnyu['second'])+float(shinnyu['third']))/3),1)}
    
    #frame7の定義する
    frame7 = ttk.Frame(root)
    #frame7の中にラベルを作る
    label239 = tk.Label(frame7, text ="針入度", relief ="groove",width=12,height=4)
    label239.grid(row = 0, column = 0)
    #frame7の場所を指定する
    frame7.place(x=11,y=500)
    #frame8の定義する
    frame8 = ttk.Frame(root)
    #frame8の中にラベルを作る
    label240 = tk.Label(frame8, text =shinnyu["first"], relief ="groove",width=6)
    label240.grid(row = 0, column = 0)
    label241 = tk.Label(frame8, text =shinnyu['second'], relief ="groove",width=6)
    label241.grid(row = 1, column = 0)
    label242 = tk.Label(frame8, text =shinnyu['third'], relief ="groove",width=6)
    label242.grid(row = 2, column = 0)
    #frame8の場所を指定する
    frame8.place(x=101,y=501)
    #frame9の定義する
    frame9 = ttk.Frame(root)
    #frame9の中にラベルを作る
    label243 = tk.Label(frame9, text =average["av"], relief ="groove",width=6,height=4)
    label243.grid(row = 0, column = 0)
    #frame9の場所を指定する
    frame9.place(x=149,y=500)

    return average


def accumulation(root, ttk, tk, kaseki, zanryu):
    
    tuuka = {
    	'26.5': round(100-float(zanryu[("26.5")]),1),
        '19.0': round(100-float(zanryu[("19.0")]),1),
        '13.2': round(100-float(zanryu[("13.2")]),1),
        '4.75': round(100-float(zanryu[('4.75')]),1),
        '2.36': round(100-float(zanryu[("2.36")]),1),
        '0.60': round(100-float(zanryu[("0.60")]),1),
        '0.30': round(100-float(zanryu[('0.30')]),1),
        '0.15': round(100-float(zanryu[("0.15")]),1),
        '0.075': round(100-float(zanryu[("0.075")]),1),
        'total': round(100-float(zanryu[('total')]),1)}
    
    #frameを定義する
    frame1 = ttk.Frame(root)
    #frameの中のラベルを作る
    label4 = tk.Label(frame1, text =" ", relief ="groove",width=8)
    label4.grid(row = 0, column = 0)
    label5 = tk.Label(frame1, text ="加積残留(g)", relief ="groove",width=15)
    label5.grid(row = 0, column = 1)
    label6 = tk.Label(frame1, text ="加積残留(%)", relief ="groove",width=15)
    label6.grid(row = 0, column = 2)
    label7 = tk.Label(frame1, text ="加積通過(%)", relief ="groove",width=15)
    label7.grid(row = 0, column = 3)
    label8 = tk.Label(frame1, text ="53.0", relief ="groove",width=8)
    label8.grid(row = 1, column = 0)
    label9 = tk.Label(frame1, text =" ", relief ="groove",width=15)
    label9.grid(row = 1, column = 1)
    label10 = tk.Label(frame1, text =" ", relief ="groove",width=15)
    label10.grid(row = 1, column = 2)
    label11 = tk.Label(frame1, text =" ", relief ="groove",width=15)
    label11.grid(row = 1, column = 3)
    label12 = tk.Label(frame1, text ="37.5", relief ="groove",width=8)
    label12.grid(row = 2, column = 0)
    label13 = tk.Label(frame1, text =" ", relief ="groove",width=15)
    label13.grid(row = 2, column = 1)
    label14 = tk.Label(frame1, text =" ", relief ="groove",width=15)
    label14.grid(row = 2, column = 2)
    label15 = tk.Label(frame1, text =" ", relief ="groove",width=15)
    label15.grid(row = 2, column = 3)
    label16 = tk.Label(frame1, text ="26.5", relief ="groove",width=8)
    label16.grid(row = 3, column = 0)
    label17 = tk.Label(frame1, text =" ", relief ="groove",width=15)
    label17.grid(row = 3, column = 1)
    label18 = tk.Label(frame1, text =" ", relief ="groove",width=15)
    label18.grid(row = 3, column = 2)
    label19 = tk.Label(frame1, text ="100.0", relief ="groove",width=15)
    label19.grid(row = 3, column = 3)
    label20 = tk.Label(frame1, text ="19.0", relief ="groove",width=8)
    label20.grid(row = 4, column = 0)
    label21 = tk.Label(frame1, text =kaseki["19.0"], relief ="groove",width=15)
    label21.grid(row = 4, column = 1)
    label22 = tk.Label(frame1, text =zanryu["19.0"], relief ="groove",width=15)
    label22.grid(row = 4, column = 2)
    label23 = tk.Label(frame1, text =tuuka["19.0"], relief ="groove",width=15)
    label23.grid(row = 4, column = 3)
    label24 = tk.Label(frame1, text ="13.2", relief ="groove",width=8)
    label24.grid(row = 5, column = 0)
    label25 = tk.Label(frame1, text =kaseki["13.2"], relief ="groove",width=15)
    label25.grid(row = 5, column = 1)
    label26 = tk.Label(frame1, text =zanryu["13.2"], relief ="groove",width=15)
    label26.grid(row = 5, column = 2)
    label27 = tk.Label(frame1, text =tuuka["13.2"], relief ="groove",width=15)
    label27.grid(row = 5, column = 3)
    label28 = tk.Label(frame1, text ="4.75", relief ="groove",width=8)
    label28.grid(row = 6, column = 0)
    label29 = tk.Label(frame1, text =kaseki["4.75"], relief ="groove",width=15)
    label29.grid(row = 6, column = 1)
    label30 = tk.Label(frame1, text =zanryu["4.75"], relief ="groove",width=15)
    label30.grid(row = 6, column = 2)
    label31 = tk.Label(frame1, text =tuuka["4.75"], relief ="groove",width=15)
    label31.grid(row = 6, column = 3)
    label32 = tk.Label(frame1, text ="2.36", relief ="groove",width=8)
    label32.grid(row = 7, column = 0)
    label33 = tk.Label(frame1, text =kaseki["2.36"], relief ="groove",width=15)
    label33.grid(row = 7, column = 1)
    label34 = tk.Label(frame1, text =zanryu["2.36"], relief ="groove",width=15)
    label34.grid(row = 7, column = 2)
    label35 = tk.Label(frame1, text =tuuka["2.36"], relief ="groove",width=15)
    label35.grid(row = 7, column = 3)
    label36 = tk.Label(frame1, text ="0.6", relief ="groove",width=8)
    label36.grid(row = 8, column = 0)
    label37 = tk.Label(frame1, text =kaseki["0.60"], relief ="groove",width=15)
    label37.grid(row = 8, column = 1)
    label38 = tk.Label(frame1, text =zanryu["0.60"], relief ="groove",width=15)
    label38.grid(row = 8, column = 2)
    label39 = tk.Label(frame1, text =tuuka["0.60"], relief ="groove",width=15)
    label39.grid(row = 8, column = 3)
    label40 = tk.Label(frame1, text ="0.3", relief ="groove",width=8)
    label40.grid(row = 9, column = 0)
    label41 = tk.Label(frame1, text =kaseki["0.30"], relief ="groove",width=15)
    label41.grid(row = 9, column = 1)
    label42 = tk.Label(frame1, text =zanryu["0.30"], relief ="groove",width=15)
    label42.grid(row = 9, column = 2)
    label43 = tk.Label(frame1, text =tuuka["0.30"], relief ="groove",width=15)
    label43.grid(row = 9, column = 3)
    label44 = tk.Label(frame1, text ="0.15", relief ="groove",width=8)
    label44.grid(row = 10, column = 0)
    label45 = tk.Label(frame1, text =kaseki["0.15"], relief ="groove",width=15)
    label45.grid(row = 10, column = 1)
    label46 = tk.Label(frame1, text =zanryu["0.15"], relief ="groove",width=15)
    label46.grid(row = 10, column = 2)
    label47 = tk.Label(frame1, text =tuuka["0.15"], relief ="groove",width=15)
    label47.grid(row = 10, column = 3)
    label48 = tk.Label(frame1, text ="0.075", relief ="groove",width=8)
    label48.grid(row = 11, column = 0)
    label49 = tk.Label(frame1, text =kaseki["0.075"], relief ="groove",width=15)
    label49.grid(row = 11, column = 1)
    label50 = tk.Label(frame1, text =zanryu["0.075"], relief ="groove",width=15)
    label50.grid(row = 11, column = 2)
    label51 = tk.Label(frame1, text =tuuka["0.075"], relief ="groove",width=15)
    label51.grid(row = 11, column = 3)
    label52 = tk.Label(frame1, text ="計", relief ="groove",width=8)
    label52.grid(row = 12, column = 0)
    label53 = tk.Label(frame1, text =kaseki["total"], relief ="groove",width=15)
    label53.grid(row = 12, column = 1)
    label54 = tk.Label(frame1, text =zanryu["total"], relief ="groove",width=15)
    label54.grid(row = 12, column = 2)
    label55 = tk.Label(frame1, text =tuuka["total"], relief ="groove",width=15)
    label55.grid(row = 12, column = 3)
    #frameの場所を指定する
    frame1.place(x=440,y=90)

    return tuuka


def extraction(root, tk, ttk, tuuka):
    
    kanri = {
    '26.5':round(float(tuuka['26.5'])-100,1),
    '19.0':round(float(tuuka['19.0'])-100,1),
    '13.2':round(float(tuuka['13.2'])-99.0,1),
    '4.75':round(float(tuuka['4.75'])-65.9,1),
    '2.36':round(float(tuuka['2.36'])-45.0,1),
    '0.60':round(float(tuuka['0.60'])-26.1,1),
    '0.30':round(float(tuuka['0.30'])-17.6,1),
    '0.15':round(float(tuuka['0.15'])-9.3,1),
    '0.075':round(float(tuuka['0.075'])-5.7,1)}
    
    #frame4を定義する
    frame4 = ttk.Frame(root)
    #frame4の中のラベルを作る
    label109 = tk.Label(frame4, text =" ", relief ="groove",width=10)
    label109.grid(row = 0, column = 0)
    label110 = tk.Label(frame4, text ="割合", relief ="groove",width=5)
    label110.grid(row = 0, column = 1)
    label111 = tk.Label(frame4, text ="53.0", relief ="groove",width=5)
    label111.grid(row = 0, column = 2)
    label112 = tk.Label(frame4, text ="37.5", relief ="groove",width=5)
    label112.grid(row = 0, column = 3)
    label113 = tk.Label(frame4, text ="26.5", relief ="groove",width=5)
    label113.grid(row = 0, column = 4)
    label114 = tk.Label(frame4, text ="19.0", relief ="groove",width=5)
    label114.grid(row = 0, column = 5)
    label115 = tk.Label(frame4, text ="13.2", relief ="groove",width=5)
    label115.grid(row = 0, column = 6)
    label116 = tk.Label(frame4, text ="4.75", relief ="groove",width=5)
    label116.grid(row = 0, column = 7)
    label117 = tk.Label(frame4, text ="2.36", relief ="groove",width=5)
    label117.grid(row = 0, column = 8)
    label118 = tk.Label(frame4, text ="0.60", relief ="groove",width=5)
    label118.grid(row = 0, column = 9)
    label119 = tk.Label(frame4, text ="0.30", relief ="groove",width=5)
    label119.grid(row = 0, column = 10)
    label120 = tk.Label(frame4, text ="0.15", relief ="groove",width=5)
    label120.grid(row = 0, column = 11)
    label121 = tk.Label(frame4, text ="0.075", relief ="groove",width=5)
    label121.grid(row = 0, column = 12)
    label122 = tk.Label(frame4, text ="5BIN", relief ="groove",width=10)
    label122.grid(row = 1, column = 0)
    label123 = tk.Label(frame4, text ="0.0", relief ="groove",width=5)
    label123.grid(row = 1, column = 1)
    label124 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label124.grid(row = 1, column = 2)
    label125 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label125.grid(row = 1, column = 3)
    label126 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label126.grid(row = 1, column = 4)
    label127 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label127.grid(row = 1, column = 5)
    label128 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label128.grid(row = 1, column = 6)
    label129 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label129.grid(row = 1, column = 7)
    label130 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label130.grid(row = 1, column = 8)
    label131 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label131.grid(row = 1, column = 9)
    label132 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label132.grid(row = 1, column = 10)
    label133 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label133.grid(row = 1, column = 11)
    label134 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label134.grid(row = 1, column = 12)
    label135 = tk.Label(frame4, text ="4BIN", relief ="groove",width=10)
    label135.grid(row = 2, column = 0)
    label136 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label136.grid(row = 2, column = 1)
    label137 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label137.grid(row = 2, column = 2)
    label138 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label138.grid(row = 2, column = 3)
    label139 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label139.grid(row = 2, column = 4)
    label140 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label140.grid(row = 2, column = 5)
    label141 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label141.grid(row = 2, column = 6)
    label142 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label142.grid(row = 2, column = 7)
    label143 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label143.grid(row = 2, column = 8)
    label144 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label144.grid(row = 2, column = 9)
    label145 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label145.grid(row = 2, column = 10)
    label146 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label146.grid(row = 2, column = 11)
    label147 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label147.grid(row = 2, column = 12)
    label148 = tk.Label(frame4, text ="3BIN", relief ="groove",width=10)
    label148.grid(row = 3, column = 0)
    label149 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label149.grid(row = 3, column = 1)
    label150 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label150.grid(row = 3, column = 2)
    label151 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label151.grid(row = 3, column = 3)
    label152 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label152.grid(row = 3, column = 4)
    label153 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label153.grid(row = 3, column = 5)
    label154 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label154.grid(row = 3, column = 6)
    label155 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label155.grid(row = 3, column = 7)
    label156 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label156.grid(row = 3, column = 8)
    label157 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label157.grid(row = 3, column = 9)
    label158 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label158.grid(row = 3, column = 10)
    label159 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label159.grid(row = 3, column = 11)
    label160 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label160.grid(row = 3, column = 12)
    label161 = tk.Label(frame4, text ="2BIN", relief ="groove",width=10)
    label161.grid(row = 4, column = 0)
    label162 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label162.grid(row = 4, column = 1)
    label163 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label163.grid(row = 4, column = 2)
    label164 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label164.grid(row = 4, column = 3)
    label165 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label165.grid(row = 4, column = 4)
    label166 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label166.grid(row = 4, column = 5)
    label167 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label167.grid(row = 4, column = 6)
    label168 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label168.grid(row = 4, column = 7)
    label169 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label169.grid(row = 4, column = 8)
    label170 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label170.grid(row = 4, column = 9)
    label171 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label171.grid(row = 4, column = 10)
    label172 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label172.grid(row = 4, column = 11)
    label173 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label173.grid(row = 4, column = 12)
    label174 = tk.Label(frame4, text ="1BIN", relief ="groove",width=10)
    label174.grid(row = 5, column = 0)
    label175 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label175.grid(row = 5, column = 1)
    label176 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label176.grid(row = 5, column = 2)
    label177 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label177.grid(row = 5, column = 3)
    label178 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label178.grid(row = 5, column = 4)
    label179 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label179.grid(row = 5, column = 5)
    label180 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label180.grid(row = 5, column = 6)
    label181 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label181.grid(row = 5, column = 7)
    label182 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label182.grid(row = 5, column = 8)
    label183 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label183.grid(row = 5, column = 9)
    label184 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label184.grid(row = 5, column = 10)
    label185 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label185.grid(row = 5, column = 11)
    label186 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label186.grid(row = 5, column = 12)
    label187 = tk.Label(frame4, text ="石粉", relief ="groove",width=10)
    label187.grid(row = 6, column = 0)
    label188 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label188.grid(row = 6, column = 1)
    label189 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label189.grid(row = 6, column = 2)
    label190 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label190.grid(row = 6, column = 3)
    label191 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label191.grid(row = 6, column = 4)
    label192 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label192.grid(row = 6, column = 5)
    label193 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label193.grid(row = 6, column = 6)
    label194 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label194.grid(row = 6, column = 7)
    label195 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label195.grid(row = 6, column = 8)
    label196 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label196.grid(row = 6, column = 9)
    label197 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label197.grid(row = 6, column = 10)
    label198 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label198.grid(row = 6, column = 11)
    label199 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label199.grid(row = 6, column = 12)
    label200 = tk.Label(frame4, text ="抽出粒度", relief ="groove",width=10)
    label200.grid(row = 7, column = 0)
    label201 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label201.grid(row = 7, column = 1)
    label202 = tk.Label(frame4, text ="100.0", relief ="groove",width=5)
    label202.grid(row = 7, column = 2)
    label203 = tk.Label(frame4, text ="100.0", relief ="groove",width=5)
    label203.grid(row = 7, column = 3)
    label204 = tk.Label(frame4, text ="100.0", relief ="groove",width=5)
    label204.grid(row = 7, column = 4)
    label205 = tk.Label(frame4, text ="100.0", relief ="groove",width=5)
    label205.grid(row = 7, column = 5)
    label206 = tk.Label(frame4, text ="100.0", relief ="groove",width=5)
    label206.grid(row = 7, column = 6)
    label207 = tk.Label(frame4, text ="79.2", relief ="groove",width=5)
    label207.grid(row = 7, column = 7)
    label208 = tk.Label(frame4, text ="60.6", relief ="groove",width=5)
    label208.grid(row = 7, column = 8)
    label209 = tk.Label(frame4, text ="35.6", relief ="groove",width=5)
    label209.grid(row = 7, column = 9)
    label210 = tk.Label(frame4, text ="24.8", relief ="groove",width=5)
    label210.grid(row = 7, column = 10)
    label211 = tk.Label(frame4, text ="13.2", relief ="groove",width=5)
    label211.grid(row = 7, column = 11)
    label212 = tk.Label(frame4, text ="7.1", relief ="groove",width=5)
    label212.grid(row = 7, column = 12)
    label213 = tk.Label(frame4, text ="目標粒度", relief ="groove",width=10)
    label213.grid(row = 8, column = 0)
    label214 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label214.grid(row = 8, column = 1)
    label215 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label215.grid(row = 8, column = 2)
    label216 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label216.grid(row = 8, column = 3)
    label217 = tk.Label(frame4, text ="100.0", relief ="groove",width=5)
    label217.grid(row = 8, column = 4)
    label218 = tk.Label(frame4, text ="100.0", relief ="groove",width=5)
    label218.grid(row = 8, column = 5)
    label219 = tk.Label(frame4, text ="99.0", relief ="groove",width=5)
    label219.grid(row = 8, column = 6)
    label220 = tk.Label(frame4, text ="65.9", relief ="groove",width=5)
    label220.grid(row = 8, column = 7)
    label221 = tk.Label(frame4, text ="45.0", relief ="groove",width=5)
    label221.grid(row = 8, column = 8)
    label222 = tk.Label(frame4, text ="26.1", relief ="groove",width=5)
    label222.grid(row = 8, column = 9)
    label223 = tk.Label(frame4, text ="17.6", relief ="groove",width=5)
    label223.grid(row = 8, column = 10)
    label224 = tk.Label(frame4, text ="9.3", relief ="groove",width=5)
    label224.grid(row = 8, column = 11)
    label225 = tk.Label(frame4, text ="5.7", relief ="groove",width=5)
    label225.grid(row = 8, column = 12)
    label226 = tk.Label(frame4, text ="管理状況", relief ="groove",width=10)
    label226.grid(row = 9, column = 0)
    label227 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label227.grid(row = 9, column = 1)
    label228 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label228.grid(row = 9, column = 2)
    label229 = tk.Label(frame4, text =" ", relief ="groove",width=5)
    label229.grid(row = 9, column = 3)
    label230 = tk.Label(frame4, text =kanri["26.5"], relief ="groove",width=5)
    label230.grid(row = 9, column = 4)
    label231 = tk.Label(frame4, text =kanri["19.0"], relief ="groove",width=5)
    label231.grid(row = 9, column = 5)
    label232 = tk.Label(frame4, text =kanri["13.2"], relief ="groove",width=5)
    label232.grid(row = 9, column = 6)
    label233 = tk.Label(frame4, text =kanri["4.75"], relief ="groove",width=5)
    label233.grid(row = 9, column = 7)
    label234 = tk.Label(frame4, text =kanri["2.36"], relief ="groove",width=5)
    label234.grid(row = 9, column = 8)
    label235 = tk.Label(frame4, text =kanri["0.60"], relief ="groove",width=5)
    label235.grid(row = 9, column = 9)
    label236 = tk.Label(frame4, text =kanri["0.30"], relief ="groove",width=5)
    label236.grid(row = 9, column = 10)
    label237 = tk.Label(frame4, text =kanri["0.15"], relief ="groove",width=5)
    label237.grid(row = 9, column = 11)
    label238 = tk.Label(frame4, text =kanri["0.075"], relief ="groove",width=5)
    label238.grid(row = 9, column = 12)
    #frame4の場所を指定する
    frame4.place(x=260,y=390)

    return kanri
